apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-app  # ✅ Must match what you expect
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-app  # ✅ Must match your deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
